# Generated by Django 5.0.6 on 2026-09-25 18:58

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=core.models.upload_to, validators=[core.validators.validate_extensao_arquivo, core.validators.validate_tamanho_arquivo], verbose_name='arquivo'),
        ),
    ]
