# Generated by Django 5.0.6 on 2026-09-26 03:32

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=core.models.upload_to, validators=[core.validators.validate_nome_arquivo, core.validators.validate_extensao_arquivo, core.validators.validate_tamanho_arquivo, core.validators.validate_conteudo_arquivo], verbose_name='arquivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=200, validators=[core.validators.validate_texto_seguro], verbose_name='titulo'),
        ),
    ]
